version: '3.8'

services:
  # Django Backend API
  backend:
    build:
      context: ./Operations/backend
      dockerfile: Dockerfile
    container_name: jeticu-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - documents_volume:/app/documents
    env_file:
      - .env.production
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
    networks:
      - jeticu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  # Vue Frontend with Nginx
  frontend:
    build:
      context: ./Operations/frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: http://backend:8000/api
    container_name: jeticu-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - media_volume:/usr/share/nginx/html/media:ro
    environment:
      - NGINX_HOST=${DOMAIN_NAME:-localhost}
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    networks:
      - jeticu-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jeticu-network:
    driver: bridge

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  documents_volume:
    driver: local