# Generated by Django 5.1.11 on 2025-08-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
