# Generated by Django 5.1.11 on 2025-08-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_staff_staffrole_staffrolemembership_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="country",
            new_name="iso_country",
        ),
        migrations.RenameField(
            model_name="airport",
            old_name="state",
            new_name="iso_region",
        ),
        migrations.RemoveField(
            model_name="airport",
            name="city",
        ),
        migrations.AddField(
            model_name="airport",
            name="gps_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="airport",
            name="ident",
            field=models.CharField(
                db_index=True, default="UTC", max_length=10, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airport",
            name="local_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="airport",
            name="municipality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
