# Generated by Django 5.1.11 on 2025-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_country_airport_iso_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="airport_type",
            field=models.CharField(
                choices=[
                    ("large_airport", "Large airport"),
                    ("medium_airport", "Medium airport"),
                    ("small_airport", "Small airport"),
                ],
                db_index=True,
                default="small_airport",
                max_length=20,
            ),
        ),
    ]
