# Generated by Django 5.1.11 on 2025-08-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_airport_airport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="icao_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=4, null=True, unique=True
            ),
        ),
    ]
