# Generated by Django 5.1.11 on 2025-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_airport_iata_code_alter_airport_icao_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
