# Generated by Django 5.1.11 on 2025-08-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_contact_date_of_birth_contact_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbo",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fbo",
            name="phone_secondary",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
