# Generated by Django 5.1.11 on 2025-08-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_fbo_phone_fbo_phone_secondary"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
