# Generated by Django 5.1.11 on 2025-08-26 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_fbo_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=50),
                ),
                ("lock", models.BooleanField(default=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREW_CHANGE", "Crew Change"),
                            ("OVERNIGHT", "Overnight (New Day)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time_local", models.DateTimeField()),
                ("start_time_utc", models.DateTimeField()),
                ("end_time_local", models.DateTimeField(blank=True, null=True)),
                ("end_time_utc", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "airport_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_events",
                        to="api.airport",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crew_line_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_events",
                        to="api.crewline",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.trip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trip_id", "start_time_utc"],
                        name="api_tripeve_trip_id_aaf262_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="api_tripeve_event_t_85f611_idx"
                    ),
                ],
            },
        ),
    ]
