# Generated by Django 5.1.11 on 2025-08-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_tripevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripevent",
            old_name="airport_id",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="tripevent",
            old_name="crew_line_id",
            new_name="crew_line",
        ),
        migrations.RenameField(
            model_name="tripevent",
            old_name="trip_id",
            new_name="trip",
        ),
        migrations.RenameIndex(
            model_name="tripevent",
            new_name="api_tripeve_trip_id_708e55_idx",
            old_name="api_tripeve_trip_id_aaf262_idx",
        ),
    ]
