# Generated by Django 5.1.11 on 2025-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial Paid"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
