# Generated by Django 5.1.11 on 2025-08-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_quote_payment_status_alter_quote_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="api.contact",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gendec", "General Declaration"),
                    ("quote", "Quote Form"),
                    ("customer_itinerary", "Customer Itinerary"),
                    ("internal_itinerary", "Internal Itinerary"),
                    ("payment_agreement", "Payment Agreement"),
                    ("consent_transport", "Consent for Transport"),
                    ("psa", "Patient Service Agreement"),
                    ("handling_request", "Handling Request"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_documents",
                to="api.passenger",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_documents",
                to="api.patient",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="api.trip",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
