# Generated by Django 5.1.11 on 2025-09-08 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_document_contact_document_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("lock", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("payment_agreement", "Payment Agreement"),
                            ("consent_transport", "Consent for Transport"),
                            ("patient_service_agreement", "Patient Service Agreement"),
                            ("medical_necessity", "Medical Necessity Agreement"),
                            ("liability_waiver", "Liability Waiver"),
                            ("hipaa_authorization", "HIPAA Authorization"),
                            ("other", "Other Contract Type"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Signature"),
                            ("signed", "Signed"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "docuseal_template_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "docuseal_submission_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "docuseal_webhook_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("signer_email", models.EmailField(max_length=254)),
                (
                    "signer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_signed", models.DateTimeField(blank=True, null=True)),
                ("date_expired", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("docuseal_response_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_contracts",
                        to="api.contact",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_contracts",
                        to="api.patient",
                    ),
                ),
                (
                    "signed_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_contracts",
                        to="api.document",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="api.trip",
                    ),
                ),
                (
                    "unsigned_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unsigned_contracts",
                        to="api.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trip", "contract_type"],
                        name="api_contrac_trip_id_f14c4b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="api_contrac_status_b0d65d_idx"
                    ),
                    models.Index(
                        fields=["docuseal_submission_id"],
                        name="api_contrac_docusea_d20cde_idx",
                    ),
                ],
            },
        ),
    ]
