# Generated by Django 5.1.11 on 2025-09-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_contract_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="authorize_net_trans_id",
            field=models.CharField(
                blank=True,
                help_text="Authorize.Net Transaction ID",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("consent_transport", "Consent for Transport"),
                    ("payment_agreement", "Air Ambulance Payment Agreement"),
                    ("patient_service_agreement", "Patient Service Agreement"),
                ],
                max_length=30,
            ),
        ),
    ]
