# Generated by Django 5.1.11 on 2025-09-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_migrate_cancelled_to_lost"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="insurance_card",
            field=models.ForeignKey(
                blank=True,
                db_column="insurance_card_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insurance_card_patients",
                to="api.document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gendec", "General Declaration"),
                    ("quote", "Quote Form"),
                    ("customer_itinerary", "Customer Itinerary"),
                    ("internal_itinerary", "Internal Itinerary"),
                    ("payment_agreement", "Payment Agreement"),
                    ("consent_transport", "Consent for Transport"),
                    ("psa", "Patient Service Agreement"),
                    ("handling_request", "Handling Request"),
                    ("letter_of_medical_necessity", "Letter of Medical Necessity"),
                    ("insurance_card", "Insurance Card"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
