# Generated by Django 5.1.11 on 2025-09-16 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_patient_insurance_card_alter_document_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=50),
                ),
                ("lock", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("activation", "Account Activation"),
                            ("password_reset", "Password Reset"),
                        ],
                        default="activation",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="api_useract_token_0c7342_idx"),
                    models.Index(
                        fields=["email", "token_type"],
                        name="api_useract_email_6aec2a_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"],
                        name="api_useract_expires_ee5d40_idx",
                    ),
                ],
            },
        ),
    ]
