# Generated by Django 5.1.11 on 2025-09-19 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_userprofile_mfa_enabled_userprofile_phone_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="useractivationtoken",
            name="api_useract_token_0c7342_idx",
        ),
        migrations.RemoveField(
            model_name="smsverificationcode",
            name="code",
        ),
        migrations.RemoveField(
            model_name="useractivationtoken",
            name="token",
        ),
        migrations.AddField(
            model_name="agreement",
            name="destination_email_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted destination email", null=True
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="destination_email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for email searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_line1_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted address line 1", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_line2_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted address line 2", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="business_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted business name", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="city_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted city", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="country_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted country", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="date_of_birth_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted email", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for email searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted first name", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted last name", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="nationality_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted nationality", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_expiration_date_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport expiration date", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_number_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport number", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="passport_number_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for passport searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted phone", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for phone searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="state_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted state", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="zip_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted ZIP code", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="notes_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted notes", null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="signer_email_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted signer email", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signer_email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for email searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signer_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted signer name", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="contact_number_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted contact number", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="contact_number_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for contact number searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="date_of_birth_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="nationality_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted nationality", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="notes_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted notes", null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="passport_expiration_date_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport expiration date", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="passport_number_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport number", null=True
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="passport_number_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for passport searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="nationality_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted nationality", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="passport_expiration_date_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport expiration date", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="passport_number_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted passport number", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="passport_number_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for passport searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="special_instructions_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted special instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="medical_team_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted medical team", null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_pdf_email_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted quote PDF email", null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_pdf_email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for email searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smsverificationcode",
            name="code_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the verification code",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="email_chain_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted email chain", null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="notes_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted notes", null=True),
        ),
        migrations.AddField(
            model_name="useractivationtoken",
            name="token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the token",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_line1_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted address line 1", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_line2_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted address line 2", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted city", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted country", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted email", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for email searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted first name", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted last name", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted phone", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC hash for phone searches",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state_encrypted",
            field=models.TextField(blank=True, help_text="Encrypted state", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zip_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted ZIP code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="medical_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RN/RN", "RN/RN"),
                    ("RN/Paramedic", "RN/Paramedic"),
                    ("RN/MD", "RN/MD"),
                    ("RN/RT", "RN/RT"),
                    ("standard", "Standard"),
                    ("full", "Full"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["destination_email_hash"], name="api_agreeme_destina_05e94f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["email_hash"], name="api_contact_email_h_06c62a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["phone_hash"], name="api_contact_phone_h_1e96ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["passport_number_hash"], name="api_contact_passpor_77df3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["signer_email_hash"], name="api_contrac_signer__602eca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(
                fields=["passport_number_hash"], name="api_passeng_passpor_8a7678_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(
                fields=["contact_number_hash"], name="api_passeng_contact_9e4df6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["passport_number_hash"], name="api_patient_passpor_7b1010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_pdf_email_hash"], name="api_quote_quote_p_765c8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivationtoken",
            index=models.Index(
                fields=["token_hash"], name="api_useract_token_h_4c9dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["email_hash"], name="api_userpro_email_h_3babfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["phone_hash"], name="api_userpro_phone_h_15369f_idx"
            ),
        ),
    ]
