# Generated by Django 5.1.11 on 2025-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_add_encrypted_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="passport_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
