# Generated by Django 5.1.11 on 2025-09-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_make_patient_legacy_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote_pdf_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
