# Generated by Django 5.1.11 on 2025-09-30 03:30

from django.db import migrations, models
import re


def initialize_trip_number_sequence(apps, schema_editor):
    """
    Initialize the trip number sequence with the highest existing numeric trip number.
    """
    Trip = apps.get_model('api', 'Trip')
    TripNumberSequence = apps.get_model('api', 'TripNumberSequence')

    # Find the highest numeric trip number in existing data
    max_numeric = 0

    for trip in Trip.objects.all():
        if trip.trip_number and not trip.trip_number.startswith('DRAFT'):
            # Extract numeric part from trip number
            match = re.search(r'\d+', trip.trip_number)
            if match:
                try:
                    num = int(match.group())
                    max_numeric = max(max_numeric, num)
                except ValueError:
                    continue

    # Initialize the sequence with the highest number found
    TripNumberSequence.objects.create(
        id=1,
        current_number=max_numeric
    )

    print(f"Initialized trip number sequence with current_number={max_numeric}")


def reverse_initialize_trip_number_sequence(apps, schema_editor):
    """
    Reverse the initialization by deleting the sequence record.
    """
    TripNumberSequence = apps.get_model('api', 'TripNumberSequence')
    TripNumberSequence.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_make_quote_legacy_fields_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_number",
                    models.IntegerField(
                        default=0, help_text="Current highest trip number"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time sequence was incremented"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Number Sequence",
                "verbose_name_plural": "Trip Number Sequence",
                "db_table": "trip_number_sequence",
            },
        ),
        migrations.RunPython(
            initialize_trip_number_sequence,
            reverse_initialize_trip_number_sequence,
        ),
    ]
