# Generated by Django 5.1.11 on 2025-09-30 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_add_trip_number_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=50),
                ),
                ("lock", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Unique template title", max_length=255, unique=True
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email subject line", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="HTML content from WYSIWYG editor"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("quote", "Quote"),
                            ("trip", "Trip"),
                            ("invoice", "Invoice"),
                            ("reminder", "Reminder"),
                            ("notification", "Notification"),
                            ("marketing", "Marketing"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether template is ready for use"
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this template was used",
                        null=True,
                    ),
                ),
                (
                    "send_count",
                    models.IntegerField(
                        default=0, help_text="Number of times template has been sent"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of template variable names",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description of template purpose"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="api_emailte_categor_042b33_idx",
                    ),
                    models.Index(fields=["title"], name="api_emailte_title_e310bd_idx"),
                ],
            },
        ),
    ]
