# Generated by Django 5.1.11 on 2025-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("fit_to_fly", "Fit To Fly"),
                    ("not_fit_to_fly", "Not Fit To Fly"),
                ],
                db_index=True,
                default="fit_to_fly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="aircraft_type",
            field=models.CharField(
                choices=[
                    ("60", "Learjet 60"),
                    ("30", "Learjet 30"),
                    ("TBD", "To Be Determined"),
                ],
                max_length=20,
            ),
        ),
    ]
